VOLUNTEER_ROLE = "Volunteer"
SENIOR_VOLUNTEER_ROLE = "Senior Volunteer"
OFFICER_ROLE = "Officer"
COORDINATOR_ROLE = "Pio 🐐"
WEEKLY_CHALLENGE_ROLE = "Weekly Challenger"

FIRST_CHALLENGE_ROLE = "First Challenger"
THREE_STREAK_ROLE = "On A Roll"
FIVE_STREAK_ROLE = "Consistency King"
TEN_CHALLENGES_ROLE = "eReuse Legend"
BOT_REACTIONS_ROLE = "eReuse Ambassador"
HUNDRED_MESSAGES_ROLE = "Chatterbox"
FIVE_HUNDRED_MESSAGES_ROLE = "Yapper"
TEN_FILES = "Photographer"


ADMIN_ROLES = [OFFICER_ROLE, SENIOR_VOLUNTEER_ROLE, COORDINATOR_ROLE]


CHALLENGE_PATH = "data/challenges.json"
CHALLENGE_POINTS_PATH = "data/challenge_points.json"
ACHEIVEMENTS_PATH = "data/challenge_achievements.json"
USER_STATS_PATH = "data/user_stats.json"


CHALLENGE_CHANNEL_ID = 1457312927395741797
MODERATOR_ONLY_CHANNEL_ID = 1446586140034470091
GENERAL_CHANNEL_ID = 1446585422305169610
