VOLUNTEER_ROLE = "Volunteer"
SENIOR_VOLUNTEER_ROLE = "Senior Volunteer"
OFFICER_ROLE = "Officer"
COORDINATOR_ROLE = "Pio 🐐"
WEEKLY_CHALLENGE_ROLE = "Weekly Challenger"

ADMIN_ROLES = [OFFICER_ROLE, SENIOR_VOLUNTEER_ROLE, COORDINATOR_ROLE]


CHALLENGE_PATH = "data/challenges.json"
CHALLENGE_POINTS_PATH = "data/challenge_points.json"

CHALLENGE_CHANNEL_ID = 1457312927395741797
MODERATOR_ONLY_CHANNEL_ID = 1446586140034470091
